# -------------------------------------------------------------------------------------
# Hugo Configuration
# See: https://gohugo.io/getting-started/configuration/
# -------------------------------------------------------------------------------------

title = "ZDev"
baseURL = "http://localhost:1313"

# 设置默认的语言 ["en", "zh-cn", "fr", "pl", ...]
defaultContentLanguage = "zh-cn"
languageCode = "zh-CN"
languageName = "简体中文"
disableLanguages = ["en", "zh-tw"]
# 是否包括中日韩文字
hasCJKLanguage = true
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true
relativeURLs = false
buildDrafts = false
summaryLength = 150
# ignore some build errors
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

theme = ["FixIt", "shortcode-mmt-netease", "shortcode-sponsor-log"]
