# -------------------------------------------------------------------------------------
# Menu Configuration
# See: https://fixit.lruihao.cn/theme-documentation-basics/#menu-advanced-configuration
# -------------------------------------------------------------------------------------

[[main]]
  identifier = "archives"
  pre = ""
  post = ""
  name = "归档"
  url = "/archives/"
  title = ""
  weight = 1
  [main.params]
    icon = "fa-solid fa-archive"
[[main]]
  identifier = "categories"
  parent = "archives"
  pre = ""
  post = ""
  name = "分类"
  url = "/categories/"
  title = ""
  weight = 1
  [main.params]
    icon = "fa-solid fa-folder-tree"
[[main]]
  identifier = "collections"
  parent = "archives"
  pre = ""
  post = ""
  name = "合集"
  url = "/collections/"
  title = ""
  weight = 2
  [main.params]
    icon = "fa-solid fa-layer-group"
[[main]]
  identifier = "tags"
  parent = "archives"
  pre = ""
  post = ""
  name = "标签"
  url = "/tags/"
  title = ""
  weight = 3
  [main.params]
    icon = "fa-solid fa-tags"
[[main]]
  identifier = "diy"
  pre = ""
  post = ""
  name = "实验室"
  url = "/diy/"
  title = ""
  weight = 2
  [main.params]
    icon = "fa-solid fa-flask"
[[main]]
  identifier = "home"
  parent = "diy"
  pre = ""
  post = ""
  name = "导航"
  url = "https://dev.cc"
  title = ""
  weight = 1
  [main.params]
    icon = "fa-solid fa-compass"
[[main]]
  identifier = "friends"
  pre = ""
  post = ""
  name = "友链"
  url = "/friends/"
  title = "友情链接"
  weight = 8
  [main.params]
    icon = "fa-solid fa-users"
[[main]]
  identifier = "about"
  pre = ""
  post = ""
  name = "关于"
  url = "/about/"
  title = ""
  weight = 9
  [main.params]
    icon = "fa-solid fa-user-tie"
[[main]]
  identifier = "guestbook"
  parent = "about"
  pre = ""
  post = ""
  name = "留言"
  url = "/guestbook/"
  title = ""
  weight = 1
  [main.params]
    icon = "fa-regular fa-comments"
[[main]]
  identifier = "projects"
  parent = "about"
  pre = ""
  post = ""
  name = "我的作品"
  url = "/projects/"
  title = ""
  weight = 2
  [main.params]
    icon = "fa-solid fa-laptop-code"
[[main]]
  identifier = "github"
  pre = "<i class='fa-brands fa-github fa-fw' aria-hidden='true'></i>"
  post = ""
  name = ""
  url = "https://github.com/yang2048/hugo-blog"
  title = "GitHub"
  weight = ""
  [main.params]
    class = "text-center"
    type = "mobile"
