# -------------------------------------------------------------------------------------
# Taxonomies Configuration
# See: https://gohugo.io/content-management/taxonomies/#configure-taxonomies
# -------------------------------------------------------------------------------------

_merge = "shadow"
category = "categories"
tag = "tags"
collection = "collections"
